name: openai_gpt3_api
description: A wrapper for the HTTP calls to the OpenAI API for the language model GPT-3.
version: 0.1.3
homepage: 'https://github.com/morriskurz/openai_gpt3_dart_api'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1
  json_annotation: ^4.0.1

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.11.0
  build_runner: ^2.0.2
  json_serializable: ^4.1.1


